# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dpaez <dpaez@student.42barcelona.com>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/14 00:16:51 by dpaez             #+#    #+#              #
#    Updated: 2024/09/14 00:22:24 by dpaez            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CC = cc -Wall -Wextra -Werror

HEADERS = ./includes

SRC = srcs/ft_putchar srcs/ft_putstr srcs/ft_strcmp srcs/ft_strlen srcs/ft_swap

OBJ = ft_putchar.o ft_putstr.o ft_strcmp.o ft_strlen.o ft_swap.o
